In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [5]:

df = pd.read_csv('heart.csv')
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [6]:
df['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [7]:
df['RestingECG'].unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [8]:
df['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [15]:
df = pd.get_dummies(df,drop_first=True)

In [16]:
df

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,1,0,0,1,1,0,0,1,0
914,68,144,193,1,141,3.4,1,1,0,0,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,1,0,0,0,1,0,1,1,0
916,57,130,236,0,174,0.0,1,0,1,0,0,0,0,0,1,0
917,38,138,175,0,173,0.0,0,1,0,1,0,1,0,0,0,1

In [18]:
df.columns

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'HeartDisease', 'Sex_M', 'ChestPainType_ATA', 'ChestPainType_NAP',
       'ChestPainType_TA', 'RestingECG_Normal', 'RestingECG_ST',
       'ExerciseAngina_Y', 'ST_Slope_Flat', 'ST_Slope_Up'],
      dtype='object')

In [19]:
x = df.drop('HeartDisease',axis=1)
y=df['HeartDisease']

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                918 non-null    int64
 1   RestingBP          918 non-null    int64
 2   Cholesterol        918 non-null    int64
 3   FastingBS          918 non-null    int64
 4   MaxHR              918 non-null    int64
 5   Oldpeak            918 non-null    float64
 6   HeartDisease       918 non-null    int64
 7   Sex_M              918 non-null    uint8
 8   ChestPainType_ATA  918 non-null    uint8
 9   ChestPainType_NAP  918 non-null    uint8
 10  ChestPainType_TA   918 non-null    uint8
 11  RestingECG_Normal  918 non-null    uint8
 12  RestingECG_ST      918 non-null    uint8
 13  ExerciseAngina_Y   918 non-null    uint8
 14  ST_Slope_Flat      918 non-null    uint8
 15  ST_Slope_Up        918 non-null    uint8
dtypes: float64(1), int64(6), uint8(9)
memory usage: 58.4 KB

In [30]:
pca = PCA(n_components=8)
pcaX = pca.fit_transform(x)

In [32]:
pd.DataFrame(pcaX)

,0,1,2,3,4,5,6,7
0,92.311315,-29.445651,-12.023584,-9.126078,-0.690411,0.287313,-0.251178,-0.520945
1,-17.143665,-13.736029,-31.481309,-5.492514,0.259131,-0.567620,-0.580669,0.871563
2,81.906717,38.223511,16.066019,-21.113523,-1.087066,0.855526,1.241067,-0.300800
3,13.654574,28.745909,2.732691,-10.150522,0.714002,-0.183892,-0.451647,-0.032271
4,-4.348523,18.094899,-13.440933,-4.008875,-1.379230,0.549373,-0.412867,0.868156
...,...,...,...,...,...,...,...,...
913,64.490453,1.444165,25.554464,-5.827206,0.694690,-0.366216,-0.338172,-0.013161
914,-5.472467,0.830304,-13.808851,13.275175,2.060545,0.267443,-0.658557,-0.056698
915,-69.003773,17.334602,5.339174,0.504850,0.416656,-0.377897,-0.532368,-0.221692
916,39.206761,-33.591950,-6.126429,9.049346,-0.617561,-0.931764,0.199098,-0.572659
917,-21.437564,-37.216610,-13.582028,-10.972808,-0.475177,0.102740,-0.241956,0.786574

In [34]:
xtrain,xtest,ytrain,ytest = train_test_split(pcaX,y,test_size=0.2,random_state=101)

In [35]:
svc = SVC()
svc.fit(xtrain,ytrain)

SVC()

In [36]:
ypred = svc.predict(xtest)

In [38]:
accuracy_score(ytest,ypred)

0.657608695652174

In [40]:
pca.n_components_

8

In [41]:
pca = PCA(0.95)
pcaX = pca.fit_transform(x)
xtrain,xtest,ytrain,ytest = train_test_split(pcaX,y,test_size=0.2,random_state=101)
svc = SVC()
svc.fit(xtrain,ytrain)
ypred = svc.predict(xtest)
accuracy_score(ytest,ypred)

0.6630434782608695

In [42]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=101)
svc = SVC()
svc.fit(xtrain,ytrain)
ypred = svc.predict(xtest)
accuracy_score(ytest,ypred)

0.657608695652174